"use client"

import Link from "next/link";
import { usePathname } from "next/navigation";

import "../global.css";
// export const metadata: Metadata = {
//   title: {
//     default: "Next.JS by Divyanshu",
//     template: "%s | Divyanshu",
//   },
//   description: "Generated by Next.js",
// };



const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forget-Password", href: "/forget-password" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body>
        <header className="h-[10vh] w-[100%] bg-neutral-800 tracking-widest drop-shadow-lg shadow-purple-800 font-bold text-[28px] text-neutral-200 flex justify-center items-center">
          Navbar
        </header>
        <article className="flex w-[100%]">
          <aside className="w-[50%] text-justify">{children}</aside>
          <aside className="w-[50%]">
            <ul>
              {navLinks.map((link) => {
                const isActive = pathname.startsWith(link.href);
                return (
                  <Link
                    href={link.href}
                    key={link.name}
                    className={
                      isActive ? " font-bold text-blue-900 " : "text-gray-800"
                    }
                  >
                    {link.name}
                  </Link>
                );
              })}
            </ul>
          </aside>
        </article>
        <header className="h-[10vh] w-[100%] bg-neutral-800 tracking-widest drop-shadow-lg shadow-purple-800 font-bold text-[28px] text-neutral-200 flex justify-center items-center">
          Footer
        </header>
      </body>
    </html>
  );
}
